app/__init__.py
from flask import Flask, render_template

def page_not_found(e):
    return render_template('404.html'), 404

def create_app(test_config=None):

    ''' Create and configure an instance of the Flask application. '''
    app = Flask(__name__)
    app.config.from_mapping(
    SECRET_KEY="CHANGE_THIS",
    )

    ''' Error handlers '''
    app.register_error_handler(404, page_not_found)

    ''' Apply the blueprints to the app '''
    from .blueprints.main.views import main
    from .blueprints.blog.views import blog
    app.register_blueprint(main)
    app.register_blueprint(blog, url_prefix='/blog')
    return app

app/blueprints/blog/views.py
from flask import Blueprint, render_template, url_for, request, abort
blog = Blueprint("blog", __name__)

title = "Flask Template Blog"

''' Paragraphs below retrieved from https://www.blindtextgenerator.com/lorem-ipsum '''
blog_posts = {
    1: {
        'title': 'First post, Far Far Away',
        'created': 'February 15 2020',
        'paragraphs': [
            'Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. A small river named Duden flows by their place and supplies it with the necessary regelialia.',
            'It is a paradisematic country, in which roasted parts of sentences fly into your mouth. Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.',
            'The Big Oxmox advised her not to do so, because there were thousands of bad Commas, wild Question Marks and devious Semikoli, but the Little Blind Text didn’t listen. She packed her seven versalia, put her initial into the belt and made herself on the way. When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove, the headline of Alphabet Village and the subline of her own road, the Line Lane. Pityful a rethoric question ran over her cheek, then ',
        ]
    },
    2: {
        'title': 'Clickbait title',
        'created': 'February 17 2020',
        'paragraphs': [
            'A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine.',
            'I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single stroke at the present moment; and yet I feel that I never was a greater artist than now.',
            'When, while the lovely valley teems with vapour around me, and the meridian sun strikes the upper surface of the impenetrable foliage of my trees, and but a few stray gleams steal into the inner sanctuary, I throw myself down among the tall grass by the trickling stream; and, as I lie close to the earth, a thousand unknown plants are noticed by me: when I hear the buzz of the little world among the stalks, and grow familiar with the countless indescribable forms of the insects and flies, then I feel the presence of the Almighty, who formed us in his own image, and the breath ',
        ]
    },
    3: {
        'title': 'Parts of my favorite book',
        'created': 'February 18 2020',
        'paragraphs': [
            'One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections.',
            'The bedding was hardly able to cover it and seemed ready to slide off any moment. His many legs, pitifully thin compared with the size of the rest of him, waved about helplessly as he looked. "What\'s happened to me? " he thought. It wasn\'t a dream.',
            ' His room, a proper human room although a little too small, lay peacefully between its four familiar walls. A collection of textile samples lay spread out on the table - Samsa was a travelling salesman - and above it there hung a picture that he had recently cut out of an illustrated magazine and housed in a nice, gilded frame. It showed a lady fitted out with a fur hat and fur boa who sat upright, raising a heavy fur muff that covered the whole of her lower arm towards the viewer. Gregor then turned to look out the window at the dull weather.',
        ]
    },
}

@blog.route('/')
def index():
    return render_template("blog/index.html", title = title, blog_posts = blog_posts)

@blog.route('/<int:post_id>')
def blog_post(post_id):

    if not post_id in blog_posts:
        abort(404)

    return render_template("blog/blog_post.html", title = title, blog_post = blog_posts[post_id])

app/blueprints/main/views.py
from flask import Blueprint, render_template, url_for, request
main = Blueprint("main", __name__)

@main.route('/')
def index():
    title = "Flask Template"
    return render_template("main/index.html", title = title)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    
<title>{{ title }}</title>
<!-- Bootstrap CSS to make the website pretty -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
<!-- End of bootstrap CSS-->

</head>
<body>

<!-- Bootstrap Navbar -->
<nav class="navbar navbar-expand-md bg-dark navbar-dark mb-3">
  
  <!-- Brand -->
  <a class="navbar-brand" href="#">Flask Template</a>

  <!-- Toggler/collapsibe Button -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Navbar links -->
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <li class="nav-item">
        <li class="nav-item">
            <a class="nav-link text-light" href="{{ url_for('main.index') }}">Main</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-light" href="{{ url_for('blog.index') }}">Blog</a>
        </li>
    </ul>
  </div>
</nav> 
<!-- End of Bootstrap Navbar -->

{% block content %}
{% endblock %}

</body>

<!-- Bootstrap JS, necessary for collapsible navbar -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<!-- End of Bootstrap JS-->
</html>

app/templates/blog/blog_post.html
{% extends 'base.html' %}

{% block content %}
<div class="container bg-light col-sm-12 col-md-10 col-lg-8 col-xl-4 py-1 mb-3 rounded">

<h2>{{ blog_post['title'] }}</h2>
<p>{{ blog_post['created'] }}</p>

{% for paragraph in blog_post['paragraphs'] %}
<p>{{ paragraph }}</p>
{% endfor %}

</div>
{% endblock %}

app/templates/blog/index.html
{% extends 'base.html' %}

{% block content %}
{% for post_id, post in blog_posts.items() %}

<div class="container bg-light col-sm-12 col-md-10 col-lg-8 col-xl-4 py-1 mb-3 rounded">
<h2>{{ post['title'] }}</h2>
<p>{{ post['created'] }}</p>

{# We only show the first 100 characters of each blogpost, the user has to click the link if they want more :) #}
<p>{{ post['paragraphs'][0][0:100] }}... (<a href="{{ url_for('blog.blog_post', post_id = post_id) }}">read more</a>)</p>
</div>

{% endfor %}
{% endblock %}

app/templates/main/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container bg-light col-sm-12 col-md-10 col-lg-8 col-xl-4 py-1 mb-3 rounded">

    <h1>Hello world!</h1>
    <p>This is some text about some stuff.</p>
    <p>Here is more text for you.</p>

</div>
{% endblock %}